[package]
name = "zodiac_tg_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = "0.9"
tokio = { version = "1.7", features = ["full"] }
dotenv = "0.15.0"
